### PR TITLE
Support inet6 on Debian platforms

### PR DESCRIPTION
**Pull request by martinisoft**
Related to #18 this is my stab at implementing an 'ipv6' option in the resource to switch the network interface from 'inet' to 'inet6'. Only thing missing here is adding the appropriate tests to try an ipv6 network configuration in testing, though I could try to cover it via unit tests instead if that would be preferred.

### CODE REVIEW

**Comment by martinisoft** [comment]
Thinking on this more, it may require a little more work, because if you want to create an inet and inet6 interface on the same device, this cookbook would have trouble supporting that type of setup because it's one file and template per device.

**Comment by jmccann** [comment]
@martinisoft Can you give me an example of a setup that wouldn't work?  Thanks!

Also, thanks for the PR ... will review/merge when I have some free time.

**Comment by martinisoft** [comment]
@jmccann So if I wanted to setup something like...

```
iface eth0 inet static
        address FE80::0202:B3FF:FE1E:8329
        netmask 64
        gateway FE80::0202:B3FF:FE1E:0
        dns-nameservers 2001:4860:4860::8888

iface eth0 inet6 static
        address 1.2.3.4
        netmask 255.255.255.255
        gateway 1.2.3.1
        dns-nameservers 8.8.8.8
```

I don't see a way to do that because the resource will write to the same file in the `/etc/network/interfaces.d/` folder if I declared two separate resources with the same device name.

**Comment by jmccann** [comment]
I just opened #20 for that issue.  Think it'd still be good to merge after I review this for baby steps to what you ultimately want.

**Pull request merged**
