### PR TITLE
PR - Windows 2008 R2 Support

### PR DESCRIPTION
**Pull request by dfduarte**
Support for Windows 2008R2, according to Issue #14 .

Changes:

* README.md with the new information
* Creation of powershell_installer.md

### CODE REVIEW

**Comment by jmccann** [comment]
Could you clean up the ruby styling per: https://travis-ci.org/target/network_interfaces_v2-cookbook/jobs/85409017#L230-L254?

Other then that this PR looks good to me.

Thanks!

**Comment by dfduarte** [comment]
Fixes on formatation of code and indentation - done

**Comment by dfduarte** [comment]
Fixed: Spaces after pounds (My bad)

**Comment by jmccann** [comment]
Thanks!

**Pull request merged**
