### PR TITLE
Add dns_nameservers for Debian.

### PR DESCRIPTION
**Pull request by diegobill**
Add dns_nameservers for Debian.

### CODE REVIEW

**Comment by jmccann** [comment]
Thanks for the PR!  We would definitely be happy to include `dns` for debian systems.

I don't think this PR in itself is enough for debian DNS support.  Some things that I noticed:
* There are no tests for the feature
 * Example @ https://github.com/target/network_interfaces_v2-cookbook/blob/master/spec/helper_recipes/fake_default_spec.rb#L176 of how to render_file with ChefSpec to make sure files can generate as expected
* `dns` is not a parameter of the `debian_network_interface` provider
 * No way to declare as part of resource a `dns` value to propagate down to the template
* `metadata.rb` is modified
 * I'd prefer to leave the `metadata.rb` maintainer and version alone.
* `CHANGELOG.md` is modified
 * I prefer to update `CHANGELOG.md` before new version release

As it is you've only updated the template file but the [debian_network_interface provider](https://github.com/target/network_interfaces_v2-cookbook/blob/master/libraries/provider_debian_network_interface.rb#L74-L95) and [debian_network_interface resource](https://github.com/target/network_interfaces_v2-cookbook/blob/master/libraries/resource_debian_network_interface.rb) need to be updated also ... as well as including tests to demonstrate the feature works.

Thanks!

**Comment by jmccann** [comment]
If you remove updates from `metadata.rb` and `CHANGELOG.md` I would probably merge this and add the testing I want myself.

Thanks!

**Comment by jmccann** [comment]
@diegobill Would you mind taking a look at some updates I made to your updates? :wink: I rebased your code onto current master and did a little refactoring.

https://github.com/target/network_interfaces_v2-cookbook/compare/diegobill-master

If that looks good I'll merge that branch and close this PR.

Thanks!

**Comment by diegobill** [comment]
@jmccann , It is looks good. You can merge now.

Thanks!

**Comment by jmccann** [comment]
Done, thanks!

**Pull request closed without merging**
